
image: node

stages:          
  - test
  - build

lint-test-job:  
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - npm i eslint
    - node_modules/eslint/bin/eslint.js .

build-image:
  stage: build
  image: docker:20.10.10
  services:
        - docker:20.10.10-dind
  rules:
   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
