
image: node

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:          
  - test

lint-test-job:  
  stage: test    
  script:
    - cd DocManagerUI  
    - npm i eslint
    - node_modules/eslint/bin/eslint.js .

